[versions]
# plugins
android-gradle                      = "8.3.0"
detekt                              = "1.23.5"
detekt-compose-rules                = "0.3.11"
junit                               = "1.10.0.0"
ksp                                 = "1.9.22-1.0.17"
ktlint                              = "3.16.0"

# production libraries
biometric                           = "1.2.0-alpha05"
compose-bom                         = "2024.02.00"
compose-compiler                    = "1.5.9"
datastore                           = "1.0.0"
hilt                                = "2.50"
kotlin                              = "1.9.22"
kotlin-coroutines                   = "1.7.3"
kotlin-datetime                     = "0.5.0"
kotlin-serialization                = "1.6.2"
kotlin-serialization-converter      = "1.0.0"
lifecycle                           = "2.7.0"
navigation                          = "2.7.7"
navigation-hilt                     = "1.1.0"
okhttp-logging-interceptor          = "4.12.0"
retrofit                            = "2.9.0"
room                                = "2.6.1"
timber                              = "5.0.1"

# test libraries
test-junit                          = "5.10.2"
test-mockk                          = "1.13.9"
test-turbine                        = "1.0.0"

# android test libraries
test-android-baseline-profile       = "1.2.3"
test-android-junit                  = "1.1.5"
test-android-profile-installer      = "1.3.1"
test-android-runner                 = "1.5.2"


[plugins]
android-application                 = { id = "com.android.application", version.ref = "android-gradle" }
android-library                     = { id = "com.android.library", version.ref = "android-gradle" }
android-test                        = { id = "com.android.test", version.ref = "android-gradle" }
baseline-profile                    = { id = "androidx.baselineprofile", version.ref = "test-android-baseline-profile" }
detekt                              = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt                                = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit                               = { id = "de.mannodermaus.android-junit5", version.ref = "junit" }
kotlin                              = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize                    = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization                = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint                              = { id = "org.jmailen.kotlinter", version.ref = "ktlint" }


[libraries]
# production libraries
biometric                           = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }
compose-bom                         = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3                   = { group = "androidx.compose.material3", name = "material3" }
datastore                           = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
detekt-compose-rules                = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose-rules" }
hilt                                = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler                       = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlin-coroutines                   = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-datetime                     = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-serialization                = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-converter      = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlin-serialization-converter" }
lifecycle-runtime-compose           = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation                          = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigation-hilt                     = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "navigation-hilt" }
okhttp-logging-interceptor          = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }
retrofit                            = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room                                = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler                       = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx                            = { module = "androidx.room:room-ktx", version.ref = "room" }
timber                              = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# test libraries
test-junit                          = { module = "org.junit.jupiter:junit-jupiter", version.ref = "test-junit" }
test-kotlin                         = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-kotlin-coroutines              = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
test-mockk                          = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-turbine                        = { module = "app.cash.turbine:turbine", version.ref = "test-turbine" }

# android test libraries
test-android-benchmark-macro        = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "test-android-baseline-profile" }
test-android-compose                = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-android-hilt                   = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
test-android-hilt-compiler          = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
test-android-junit                  = { group = "androidx.test.ext", name = "junit", version.ref = "test-android-junit" } # for @RunWith(AndroidJUnit4::class)
test-android-profile-installer      = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "test-android-profile-installer" } # for consuming baseline-prof.txt
test-android-runner                 = { module = "androidx.test:runner", version.ref = "test-android-runner" }

# debug libraries
debug-compose-manifest              = { group = "androidx.compose.ui", name = "ui-test-manifest" }


[bundles]
common-test = [
    "test-junit",
    "test-kotlin",
    "test-kotlin-coroutines",
    "test-mockk",
    "test-turbine"
]
common-android-test = [
    "test-android-compose",
    "test-android-hilt",
    "test-android-runner"
]
